#Maps as list of list, sub lists include a name, layer type, layer Config (as dict)
maps: 
  [["tsdf1", "tsdf", {voxel_size: 0.1, voxels_per_side: 16}], #voxel_size 0.1 
   ["rgb1", "rgb", {voxel_size: 0.4, voxels_per_side: 16}],
   ["thermal1", "thermal", {voxel_size: 0.4, voxels_per_side: 16}]]

#Sensors as list of lists, sub lists include the sensor_type, a config with all inputs [layer types + name, topics, working frame], a config with the integrator parameters
sensors:
  [["lidar_sensor",
    "lidar_sensor1", 
    {collision_type: "tsdf", collision_layer: "tsdf1",
    pointcloud_topic: "/scan_cloud_filtered",
    integrator_type: "simple", 
    frame: "world",
    frames_per_submap: 20,
    msg_delay: 0.1,
    use_msg_delay: true
    }, #TODO add integrator type
    {default_truncation_distance: 0.4, #not all have to be set
    max_weight: 10000.0,
    voxel_carving_enabled: true,
    min_ray_length_m: 0.1,
    max_ray_length_m: 30.0,
    use_const_weight: false,
    allow_clear: true,
    use_weight_dropoff: true,
    use_sparsity_compensation_factor: false,
    sparsity_compensation_factor: 1.0,
    #integrator_threads: 1,
    integration_order_mode: "mixed",
    enable_anti_grazing: false,
    start_voxel_subsampling_factor: 1.0,
    max_consecutive_ray_collisions: 2,
    clear_checks_every_n_frames: 1 #,
    #max_integration_time_s: 999999,
    }
   ],
   ["rgb_sensor",
    "rgb_sensor1",
    {collision_type: "tsdf", collision_layer: "tsdf1",
    rgb_layer: "rgb1",
    camera_topic: "/realsense_d435_back/color/image_raw",
    camera_info_topic: "/realsense_d435_back/color/camera_info",
    frame: "world",
    sub_sample_factor: 1.0,
    frames_per_submap: 20,
    msg_delay: 0.1,
    use_msg_delay: true,
    debug_image: false,
    debug_image_topic: "debug_image1"
    },
    {max_distance: 40.0, 
    max_weight: 100.0,
    prop_voxel_radius: 2,
    use_previous_maps: 0 #amount of additional maps data is integrated
    }
   ],
   ["thermal_sensor",
    "thermal_sensor1",
    {
    collision_type: "tsdf", collision_layer: "tsdf1",
    thermal_layer: "thermal1",
    camera_topic: "/arm_thermal_cam/image_raw",
    camera_info_topic: "/arm_thermal_cam/camera_info",
    frame: "world",
    sub_sample_factor: 1.0,
    frames_per_submap: 20,
    msg_delay: 0.1,
    use_msg_delay: true,
    normalize: true,
    min_intensity: 0.0,
    max_intensity: 40.0, #to normalize into 0.0 to 0.1
    debug_image: false,
    debug_image_topic: "debug_image2"
    },
    {max_distance: 20.0, 
    max_weight: 100.0,
    prop_voxel_radius: 2,
    use_previous_maps: 0
    }
   ]
  ]

    #visualizers as list of list, sub lists include a name , a config with two layers with types, update rate and a mesh config
visualizers:
  [
  ["visualizer1",
  "tsdf",
  {
  collision_layer_type: "tsdf", collision_layer: "tsdf1",
  color_layer_type: "tsdf", color_layer: "tsdf1",
  update_interval: 10.0,
  topic: "mesh1"
  }, 
  {
  use_color: true,
  min_weight: 0.0001 #,
  #integrator_threads: 1,
  }
  ],
  ["visualizer2",
  "rgb",
  {
  collision_layer_type: "tsdf", collision_layer: "tsdf1",
  color_layer_type: "rgb", color_layer: "rgb1",
  update_interval: 10.0,
  topic: "mesh2"
  },
  {
  use_color: true,
  min_weight: 0.0001 #,
  #integrator_threads: 1,
  }
  ],
    ["visualizer3",
  "thermal",
  {
  collision_layer_type: "tsdf", collision_layer: "tsdf1",
  color_layer_type: "thermal", color_layer: "thermal1",
  update_interval: 10.0,
  topic: "mesh3",
  },
  {
  use_color: true,
  min_weight: 0.0001 #,
  #integrator_threads: 1,
  }]
  ]

pose_graph_settings: {
  enabled: true,
  submap_anouncement_topic: "",
  submap_list_topic: "",
  min_remesh_angle_radians: 1.0,
  min_remesh_distance_meters: 0.1,
  publish_local: true 
}
